package turtley;

import java.io.ByteArrayOutputStream;
import java.io.PrintStream;
import java.nio.charset.StandardCharsets;
import java.util.Scanner;

import turtley.command.Command;
import turtley.command.Parser;
import turtley.exception.TurtleyException;
import turtley.model.TaskList;
import turtley.storage.Storage;
import turtley.ui.Ui;

/**
 * Coordinates Turtley's application components.
 */
public class Turtley {

    private final Storage storage;
    private final TaskList tasks;
    private final Ui ui;

    /**
     * Creates Turtley with the default save-file location.
     */
    public Turtley() {
        this("data/turtley.txt");
    }

    /**
     * Creates Turtley with a supplied save-file location.
     *
     * @param filePath the save-file path.
     */
    public Turtley(String filePath) {
        ui = new Ui();
        storage = new Storage(filePath);
        TaskList loadedTasks;
        try {
            loadedTasks = new TaskList(storage.load());
        } catch (TurtleyException exception) {
            ui.showError(exception);
            loadedTasks = new TaskList();
        }
        tasks = loadedTasks;
    }

    /**
     * Runs the command loop until the user exits or input ends.
     */
    public void run() {
        ui.showWelcome();
        boolean running = true;
        Scanner keyboard = new Scanner(System.in);
        while (running) {
            String input = ui.readLine(keyboard);
            if (input == null) {
                break;
            }

            Command command = executeCommand(input, ui);
            running = !command.isExit();
        }
        keyboard.close();
    }

    /**
     * Processes one user input line and returns the response for a graphical interface.
     *
     * @param input the raw user input.
     * @return the response generated by Turtley's command processing.
     */
    public String getResponse(String input) {
        ByteArrayOutputStream responseOutput = new ByteArrayOutputStream();
        try (PrintStream printStream = new PrintStream(responseOutput, true, StandardCharsets.UTF_8)) {
            Ui responseUi = new Ui(printStream, false);
            executeCommand(input, responseUi);
        }
        return responseOutput.toString(StandardCharsets.UTF_8).strip();
    }

    /**
     * Parses and executes one command using the supplied user interface.
     *
     * @param input the raw user input.
     * @param commandUi the interface that receives the command response.
     * @return the parsed command.
     */
    private Command executeCommand(String input, Ui commandUi) {
        Command command = Parser.parse(input);
        try {
            command.execute(tasks, commandUi, storage);
        } catch (TurtleyException exception) {
            commandUi.showError(exception);
        }
        return command;
    }

    /**
     * Starts Turtley with its default storage location.
     *
     * @param args command-line arguments, which are not used.
     */
    public static void main(String[] args) {
        new Turtley().run();
    }
}
