package turtley;

import java.io.ByteArrayOutputStream;
import java.io.PrintStream;
import java.nio.charset.StandardCharsets;
import java.util.Scanner;
import java.util.function.Consumer;

import turtley.command.Command;
import turtley.command.Parser;
import turtley.exception.TurtleyException;
import turtley.model.TaskList;
import turtley.storage.Storage;
import turtley.ui.Ui;

/**
 * Coordinates Turtley's application components.
 */
public class Turtley {

    /**
     * Contains a graphical-interface response and whether it should be presented as an error.
     *
     * @param text the response text.
     * @param isError whether the response represents an error.
     */
    public record Response(String text, boolean isError) {
    }

    private final Storage storage;
    private final TaskList tasks;
    private final Ui ui;

    /**
     * Creates Turtley with the default save-file location.
     */
    public Turtley() {
        this("data/turtley.txt");
    }

    /**
     * Creates Turtley with a supplied save-file location.
     *
     * @param filePath the save-file path.
     */
    public Turtley(String filePath) {
        ui = new Ui();
        storage = new Storage(filePath);
        TaskList loadedTasks;
        try {
            loadedTasks = new TaskList(storage.load());
        } catch (TurtleyException exception) {
            ui.showError(exception);
            loadedTasks = new TaskList();
        }
        tasks = loadedTasks;
    }

    /**
     * Runs the command loop until the user exits or input ends.
     */
    public void run() {
        ui.showWelcome();
        boolean isRunning = true;
        Scanner keyboard = new Scanner(System.in);
        while (isRunning) {
            String input = ui.readLine(keyboard);
            if (input == null) {
                break;
            }

            Command command = executeCommand(input, ui);
            isRunning = !command.isExit();
        }
        keyboard.close();
    }

    /**
     * Processes one user input line and returns the response for a graphical interface.
     *
     * @param input the raw user input.
     * @return the response generated by Turtley's command processing.
     */
    public String getResponse(String input) {
        return getResponseDetails(input).text();
    }

    /**
     * Processes one user input line and reports whether the response is an error.
     *
     * @param input the raw user input.
     * @return the response text and its presentation status.
     */
    public Response getResponseDetails(String input) {
        return captureResponse(responseUi -> executeCommand(input, responseUi), false);
    }

    /**
     * Returns Turtley's startup banner and greeting for a graphical interface.
     *
     * @return the startup banner and greeting.
     */
    public String getWelcomeMessage() {
        return captureResponse(Ui::showWelcome, true).text();
    }

    /**
     * Parses and executes one command using the supplied user interface.
     *
     * @param input the raw user input.
     * @param commandUi the interface that receives the command response.
     * @return the parsed command.
     */
    private Command executeCommand(String input, Ui commandUi) {
        Command command = Parser.parse(input);
        assert command != null : "Parser must return a command for every input line.";
        try {
            command.execute(tasks, commandUi, storage);
        } catch (TurtleyException exception) {
            commandUi.showError(exception);
        }
        return command;
    }

    /**
     * Captures output generated by a graphical-interface response.
     *
     * @param responseAction the action that writes the response.
     * @param shouldPreserveLeadingWhitespace whether leading whitespace is part of the response.
     * @return the captured response without console separators and its error status.
     */
    private Response captureResponse(Consumer<Ui> responseAction, boolean shouldPreserveLeadingWhitespace) {
        ByteArrayOutputStream responseOutput = new ByteArrayOutputStream();
        boolean isError;
        try (PrintStream printStream = new PrintStream(responseOutput, true, StandardCharsets.UTF_8)) {
            Ui responseUi = new Ui(printStream, false);
            responseAction.accept(responseUi);
            isError = responseUi.hasError();
        }

        String response = responseOutput.toString(StandardCharsets.UTF_8);
        String formattedResponse = shouldPreserveLeadingWhitespace ? response.stripTrailing() : response.strip();
        return new Response(formattedResponse, isError);
    }

    /**
     * Starts Turtley with its default storage location.
     *
     * @param args command-line arguments, which are not used.
     */
    public static void main(String[] args) {
        new Turtley().run();
    }
}
